"use client";

import { useState } from "react";
import { ManagerSelect } from "./ManagerSelect";

export function ReplacementModal({ battle, opponent, onClose, onSave, managerOptions = [] }: any) {
  const [creatorUsername, setCreatorUsername] = useState(""); const [manager, setManager] = useState(""); const [copied, setCopied] = useState(false);
  const time = battle.actualTime || battle.requestedTime; const dateValue = new Date(`${battle.weekStart}T12:00:00`); dateValue.setDate(dateValue.getDate() + Math.max(0, ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"].indexOf(battle.day)));
  const date = dateValue.toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long" }); const clean = (value: string) => value.trim().replace(/^@/, "");
  const preview = `*⚔️ Replacement ⚔️*\n\n📅 *${date.toUpperCase()}*\n🕣 *${new Date(`2000-01-01T${time}`).toLocaleTimeString("en-GB", { hour: "numeric", minute: "2-digit", hour12: true }).toUpperCase()}*\n\n👤 *New creator:* ${clean(creatorUsername || "creator")}\nhttps://www.tiktok.com/@${clean(creatorUsername || "username")}\n\n*Your Creator*\n⚔️ *Against:* ${opponent?.creatorUsername || "opponent"}\nhttps://www.tiktok.com/@${clean(opponent?.creatorUsername || "username")}`;
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/85 p-4"><form onSubmit={(event) => { event.preventDefault(); if (creatorUsername.trim() && manager.trim()) onSave({ creatorUsername, manager }); }} className="w-full max-w-xl rounded-3xl border border-orange-400/50 bg-[#111] p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase text-orange-300">REPLACE CREATOR</p><h2 className="mt-2 text-3xl font-black">@{battle.creatorUsername}</h2></div><button type="button" onClick={onClose} className="text-xs font-black uppercase">CLOSE</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><input required autoFocus value={creatorUsername} onChange={(event) => setCreatorUsername(event.target.value)} placeholder="NEW CREATOR NAME" className="rounded-xl border border-white/15 bg-black p-3 font-bold"/><ManagerSelect value={manager} onChange={setManager} managers={managerOptions} className="rounded-xl border border-white/15 bg-black p-3 font-bold"/></div><div className="mt-5 rounded-xl border border-white/15 bg-black p-4"><p className="text-[10px] font-black uppercase tracking-[.14em] text-white/55">TEXT TO COPY</p><pre className="mt-3 whitespace-pre-wrap font-sans text-sm text-white/85">{preview}</pre><button type="button" onClick={async () => { await navigator.clipboard.writeText(preview); setCopied(true); window.setTimeout(() => setCopied(false), 1400); }} className="mt-4 rounded-lg border border-sky-300/50 px-4 py-2 text-xs font-black uppercase text-sky-300">{copied ? "COPIED ✓" : "COPY REPLACEMENT TEXT"}</button></div><button className="mt-5 w-full rounded-xl bg-orange-400 p-4 text-xs font-black uppercase text-black">SAVE REPLACEMENT</button></form></div>;
}
